<?php

/***[JCBGUI.power.licensing_template.136.$$$$]***/
/**
 * @package    Joomla.Component.Builder
 *
 * @created    4th September, 2022
 * @author     Llewellyn van der Merwe <https://dev.vdm.io>
 * @git        Joomla Component Builder <https://git.vdm.dev/joomla/Component-Builder>
 * @copyright  Copyright (C) 2015 Vast Development Method. All rights reserved.
 * @license    GNU General Public License version 2 or later; see LICENSE.txt
 */
/***[/JCBGUI$$$$]***/

namespace JCB\Joomla\Businessdirectory;


use JCB\Joomla\Interfaces\TableInterface;
use JCB\Joomla\Abstraction\BaseTable;


/**
 * Businessdirectory Tables
 * 
 * @since 3.2.0
 */
final class Table extends BaseTable implements TableInterface
{

/***[JCBGUI.power.main_class_code.136.$$$$]***/
	/**
	 * All areas/views/tables with their field details
	 *
	 * @var     array
	 * @since 3.2.0
	 **/
	protected array $tables = [
		'company' => [
			'name' => [
				'name' => 'name',
				'label' => 'COM_BUSINESSDIRECTORY_COMPANY_NAME_LABEL',
				'type' => 'text',
				'title' => true,
				'list' => 'companies',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => '5d3d34dd-4876-4c6a-86ab-b4e162f22c08',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'city' => [
				'name' => 'city',
				'label' => 'COM_BUSINESSDIRECTORY_COMPANY_CITY_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'companies',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => '17360cdd-c3de-4af3-b24c-4a3df92861fa',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'country' => [
				'name' => 'country',
				'label' => 'COM_BUSINESSDIRECTORY_COMPANY_COUNTRY_LABEL',
				'type' => 'ModalSelect',
				'title' => false,
				'list' => 'companies',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => '8d1b9d7e-77c1-43d9-bc97-0dd021bfe779',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => [
					'type' => 1,
					'table' => '#__businessdirectory_country',
					'component' => 'com_businessdirectory',
					'entity' => 'country',
					'value' => 'name',
					'key' => 'guid',
				],
			],
			'contactname' => [
				'name' => 'contactname',
				'label' => 'COM_BUSINESSDIRECTORY_COMPANY_CONTACTNAME_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'companies',
				'store' => NULL,
				'tab_name' => 'Contact info',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => '5711daf2-43c4-4b35-9d0c-b96962062734',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'guid' => [
				'name' => 'guid',
				'label' => 'COM_BUSINESSDIRECTORY_COMPANY_GUID_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'companies',
				'store' => NULL,
				'tab_name' => 'publishing',
				'db' => [
					'type' => 'VARCHAR(36)',
					'default' => '',
					'GUID' => '5aa57bbe-7b19-4db9-915c-561863458d2b',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'portfolio' => [
				'name' => 'portfolio',
				'label' => 'COM_BUSINESSDIRECTORY_COMPANY_PORTFOLIO_LABEL',
				'type' => 'subform',
				'title' => false,
				'list' => 'companies',
				'store' => 'json',
				'tab_name' => 'Portfolio',
				'db' => [
					'type' => 'TEXT',
					'default' => 'EMPTY',
					'GUID' => '99ef0b56-e724-4a18-8a67-ee432aa5c17f',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'website' => [
				'name' => 'website',
				'label' => 'COM_BUSINESSDIRECTORY_COMPANY_WEBSITE_LABEL',
				'type' => 'url',
				'title' => false,
				'list' => 'companies',
				'store' => NULL,
				'tab_name' => 'Contact info',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => 'b84bc31f-90ba-44bc-8808-c8fb3248ccd5',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'phone' => [
				'name' => 'phone',
				'label' => 'COM_BUSINESSDIRECTORY_COMPANY_PHONE_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'companies',
				'store' => NULL,
				'tab_name' => 'Contact info',
				'db' => [
					'type' => 'VARCHAR(50)',
					'default' => '',
					'GUID' => '76886659-3578-4091-8c00-330c85f618dc',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'email' => [
				'name' => 'email',
				'label' => 'COM_BUSINESSDIRECTORY_COMPANY_EMAIL_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'companies',
				'store' => NULL,
				'tab_name' => 'Contact info',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => 'ba32af1e-0b57-4dcc-b9bb-7cec104c0ee7',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'expertise' => [
				'name' => 'expertise',
				'label' => 'COM_BUSINESSDIRECTORY_COMPANY_EXPERTISE_LABEL',
				'type' => 'tag',
				'title' => false,
				'list' => 'companies',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'TEXT',
					'default' => 'EMPTY',
					'GUID' => '875247aa-3410-44c6-b9b7-fd4c1df13133',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'companysize' => [
				'name' => 'companysize',
				'label' => 'COM_BUSINESSDIRECTORY_COMPANY_COMPANYSIZE_LABEL',
				'type' => 'list',
				'title' => false,
				'list' => 'companies',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => 'e4fff45e-0335-44f6-9dc7-54f2dc81d659',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'state' => [
				'name' => 'state',
				'label' => 'COM_BUSINESSDIRECTORY_COMPANY_STATE_LABEL',
				'type' => 'ModalSelect',
				'title' => false,
				'list' => 'companies',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => '1e666136-800a-486d-a8e8-13a054b7acde',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => [
					'type' => 1,
					'table' => '#__businessdirectory_state',
					'component' => 'com_businessdirectory',
					'entity' => 'state',
					'value' => 'name',
					'key' => 'guid',
				],
			],
			'coc' => [
				'name' => 'coc',
				'label' => 'COM_BUSINESSDIRECTORY_COMPANY_COC_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'companies',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => '1a67060a-9e45-4b3b-8be6-8025bf3a3026',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'zip' => [
				'name' => 'zip',
				'label' => 'COM_BUSINESSDIRECTORY_COMPANY_ZIP_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'companies',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => 'c404bcc1-3d32-4b9d-ad71-37f28715ac0f',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'address' => [
				'name' => 'address',
				'label' => 'COM_BUSINESSDIRECTORY_COMPANY_ADDRESS_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'companies',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => '9f7c6956-5149-4148-a698-f9bae82a0229',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'access' => [
				'name' => 'access',
				'label' => 'Access',
				'type' => 'accesslevel',
				'title' => false,
				'store' => NULL,
				'tab_name' => NULL,
				'db' => [
					'type' => 'INT(10) unsigned',
					'default' => '0',
					'key' => true,
					'null_switch' => 'NULL',
				],
			],
			'metakey' => [
				'name' => 'metakey',
				'label' => 'Meta Keywords',
				'type' => 'textarea',
				'title' => false,
				'store' => NULL,
				'tab_name' => 'publishing',
				'db' => [
					'type' => 'TEXT',
				],
			],
			'metadesc' => [
				'name' => 'metadesc',
				'label' => 'Meta Description',
				'type' => 'textarea',
				'title' => false,
				'store' => NULL,
				'tab_name' => 'publishing',
				'db' => [
					'type' => 'TEXT',
				],
			],
			'metadata' => [
				'name' => 'metadata',
				'label' => 'Meta Data',
				'type' => NULL,
				'title' => false,
				'store' => 'json',
				'tab_name' => 'publishing',
				'db' => [
					'type' => 'TEXT',
				],
			],
		],
		'country' => [
			'name' => [
				'name' => 'name',
				'label' => 'COM_BUSINESSDIRECTORY_COUNTRY_NAME_LABEL',
				'type' => 'text',
				'title' => true,
				'list' => 'countries',
				'store' => NULL,
				'tab_name' => 'States',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => '5d3d34dd-4876-4c6a-86ab-b4e162f22c08',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'guid' => [
				'name' => 'guid',
				'label' => 'COM_BUSINESSDIRECTORY_COUNTRY_GUID_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'countries',
				'store' => NULL,
				'tab_name' => 'publishing',
				'db' => [
					'type' => 'VARCHAR(36)',
					'default' => '',
					'GUID' => '5aa57bbe-7b19-4db9-915c-561863458d2b',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'access' => [
				'name' => 'access',
				'label' => 'Access',
				'type' => 'accesslevel',
				'title' => false,
				'store' => NULL,
				'tab_name' => NULL,
				'db' => [
					'type' => 'INT(10) unsigned',
					'default' => '0',
					'key' => true,
					'null_switch' => 'NULL',
				],
			],
			'metakey' => [
				'name' => 'metakey',
				'label' => 'Meta Keywords',
				'type' => 'textarea',
				'title' => false,
				'store' => NULL,
				'tab_name' => 'publishing',
				'db' => [
					'type' => 'TEXT',
				],
			],
			'metadesc' => [
				'name' => 'metadesc',
				'label' => 'Meta Description',
				'type' => 'textarea',
				'title' => false,
				'store' => NULL,
				'tab_name' => 'publishing',
				'db' => [
					'type' => 'TEXT',
				],
			],
			'metadata' => [
				'name' => 'metadata',
				'label' => 'Meta Data',
				'type' => NULL,
				'title' => false,
				'store' => 'json',
				'tab_name' => 'publishing',
				'db' => [
					'type' => 'TEXT',
				],
			],
		],
		'state' => [
			'name' => [
				'name' => 'name',
				'label' => 'COM_BUSINESSDIRECTORY_STATE_NAME_LABEL',
				'type' => 'text',
				'title' => true,
				'list' => 'states',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => '5d3d34dd-4876-4c6a-86ab-b4e162f22c08',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'country' => [
				'name' => 'country',
				'label' => 'COM_BUSINESSDIRECTORY_STATE_COUNTRY_LABEL',
				'type' => 'ModalSelect',
				'title' => false,
				'list' => 'states',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => '8d1b9d7e-77c1-43d9-bc97-0dd021bfe779',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => [
					'type' => 1,
					'table' => '#__businessdirectory_country',
					'component' => 'com_businessdirectory',
					'entity' => 'country',
					'value' => 'name',
					'key' => 'guid',
				],
			],
			'guid' => [
				'name' => 'guid',
				'label' => 'COM_BUSINESSDIRECTORY_STATE_GUID_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'states',
				'store' => NULL,
				'tab_name' => 'publishing',
				'db' => [
					'type' => 'VARCHAR(36)',
					'default' => '',
					'GUID' => '5aa57bbe-7b19-4db9-915c-561863458d2b',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'access' => [
				'name' => 'access',
				'label' => 'Access',
				'type' => 'accesslevel',
				'title' => false,
				'store' => NULL,
				'tab_name' => NULL,
				'db' => [
					'type' => 'INT(10) unsigned',
					'default' => '0',
					'key' => true,
					'null_switch' => 'NULL',
				],
			],
			'metakey' => [
				'name' => 'metakey',
				'label' => 'Meta Keywords',
				'type' => 'textarea',
				'title' => false,
				'store' => NULL,
				'tab_name' => 'publishing',
				'db' => [
					'type' => 'TEXT',
				],
			],
			'metadesc' => [
				'name' => 'metadesc',
				'label' => 'Meta Description',
				'type' => 'textarea',
				'title' => false,
				'store' => NULL,
				'tab_name' => 'publishing',
				'db' => [
					'type' => 'TEXT',
				],
			],
			'metadata' => [
				'name' => 'metadata',
				'label' => 'Meta Data',
				'type' => NULL,
				'title' => false,
				'store' => 'json',
				'tab_name' => 'publishing',
				'db' => [
					'type' => 'TEXT',
				],
			],
		],
	];/***[/JCBGUI$$$$]***/

}

